
:-(compiler_options([xpp_on,canonical])).

/********** Tabling and Trailer Control Variables ************/

#define EQUALITYnone
#define INHERITANCEflogic
#define TABLINGreactive
#define TABLINGvariant
#define CUSTOMnone

#define FLORA_INCREMENTAL_TABLING 

/************************************************************************
  file: headerinc/flrheader_inc.flh

  Author(s): Guizhen Yang

  This file is automatically included by the Flora-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).
#mode standard Prolog

#include "flrheader.flh"
#include "flora_porting.flh"

/***********************************************************************/

/************************************************************************
  file: headerinc/flrheader_prog_inc.flh

  Author(s): Michael Kifer

  This file is automatically included by the Flora-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).
#mode standard Prolog

#include "flrheader_prog.flh"

/***********************************************************************/

#define FLORA_COMPILATION_ID 19

#mode save
#mode nocomment "%"
#define FLORA_THIS_FILENAME  'tax_1040_2024.ergo'
#mode restore
/************************************************************************
  file: headerinc/flrheader2_inc.flh

  Author(s): Michael Kifer

  This file is automatically included by the Flora-2 compiler.
  It has files that must be included in the header and typically
  contain some Prolog statements. Such files cannot appear
  in flrheader.flh because flrheader.flh is included in various restricted
  contexts where Prolog statements are not allowed.

  Included ONLY IN ADDED files (compiled for addition)
************************************************************************/

:-(compiler_options([xpp_on])).

#define TABLING_CONNECTIVE  :-

%% flora_tabling_methods is included here to affect preprocessing of
%% <filename>.flt files, which contain table declarations for Prolog and
%% UDF predicates.
#include "flora_tabling_methods.flh"

%% include list of tabled predicates
#mode save
#mode nocomment "%"
#if defined(FLORA_FLT_FILENAME)
#include FLORA_FLT_FILENAME
#endif
#mode restore

/***********************************************************************/

:-(import(from(/(flora_warning_line,1),flrprint))).
?-(catch(abolish_all_tables,_,flora_warning_line('a tabled subgoal depends on ~w.~n		  The program might not function correctly.~n		  Indicator: ~w~n		  Offending module:  ~w~n		  Offending predicate: ~w~n', ['\\add', FLORA_THIS_FILENAME, FLORA_THIS_MODULE_NAME]))).
/************************************************************************
  file: syslibinc/flrdynrule_inc.flh

  Author(s): Chang Zhao

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLSYSRULEUPDATE))).

/***********************************************************************/

/************************************************************************
  file: syslibinc/flrdynrule_inc.flh

  Author(s): Chang Zhao

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLSYSRULEUPDATE))).

/***********************************************************************/

#ifndef FLORA_TABLING_METHODS_INCLUDED
#include "flora_tabling_methods.flh"
#endif
 
#if !defined(FLORA_FDB_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FDB_FILENAME  'tax_1040_2024#for_add.fdb'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FDB_FILENAME,FLORA_THIS_MODULE_NAME,'fdb'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_canonical_and_insert(FLORA_FDB_FILENAME,FLORA_THIS_FDB_STORAGE))).
#endif

 
#if !defined(FLORA_FLD_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLD_FILENAME  'tax_1040_2024#for_add.fld'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLD_FILENAME,FLORA_THIS_MODULE_NAME,'fld'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_canonical_and_insert(FLORA_FLD_FILENAME,FLORA_THIS_FLD_STORAGE))).
#endif

 
#if !defined(FLORA_FLS_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLS_FILENAME  'tax_1040_2024.fls'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLS_FILENAME,FLORA_THIS_MODULE_NAME,'fls'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_symbols_canonical_and_insert(FLORA_FLS_FILENAME,FLORA_THIS_FLS_STORAGE,_SymbolErrNum))).
#endif


%%%%%%%%%%%%%%%%%%%%%%%%%%% Rule insertion statements %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Wages',__Wages),=('?AGI',__AGI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?AGI',__AGI)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',3,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,__AGI,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(wage_income,__T,__Wages,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),fllibdelayedliteral('\\is','tax_1040_2024.ergo',40,[__AGI,__Wages])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__AGI,__T,__Wages],[__AGI,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?SelfAge',__SelfAge),=('?SelfBlind',__SelfBlind),=('?SpouseAge',__SpouseAge),=('?SpouseBlind',__SpouseBlind),=('?Count',__Count)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Count',__Count)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',14,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(qualifier_count,__T,__Count,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(age_65_or_over_flag,__T,__SelfAge,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(blind_flag,__T,__SelfBlind,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(spouse_age_65_or_over_flag,__T,__SpouseAge,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(spouse_blind_flag,__T,__SpouseBlind,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar8,__newvar1)),fllibdelayedliteral('\\is','tax_1040_2024.ergo',80,[__Count,+(+(+(__SelfAge,__SelfBlind),__SpouseAge),__SpouseBlind)]))))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Count,__SelfAge,__SelfBlind,__SpouseAge,__SpouseBlind,__T],[__Count,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?PerQual',__PerQual),=('?Count',__Count),=('?Extra',__Extra)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Extra',__Extra)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',15,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(additional_standard_deduction,__T,2025,__Extra,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(per_qualifier_additional_amount,2025,__Status,__PerQual,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(qualifier_count,__T,__Count,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),fllibdelayedliteral('\\is','tax_1040_2024.ergo',88,[__Extra,*(__PerQual,__Count)])))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Count,__Extra,__PerQual,__Status,__T],[__Extra,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?Base',__Base),=('?Extra',__Extra),=('?Amount',__Amount)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Amount',__Amount)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',16,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,__Amount,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(base_standard_deduction,2025,__Status,__Base,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(additional_standard_deduction,__T,2025,__Extra,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),fllibdelayedliteral('\\is','tax_1040_2024.ergo',96,[__Amount,+(__Base,__Extra)])))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Amount,__Base,__Extra,__Status,__T],[__Amount,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?AGI',__AGI),=('?SD',__SD),=('?TI',__TI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?TI',__TI)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',17,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,__AGI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,__SD,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',105,[__AGI,__SD]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',106,[__TI,0])))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__AGI,__SD,__T,__TI],[__T,__TI])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?AGI',__AGI),=('?SD',__SD),=('?TI',__TI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?TI',__TI)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',18,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,__AGI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,__SD,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(fllibdelayedliteral(>,'tax_1040_2024.ergo',111,[__AGI,__SD]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',112,[__TI,-(__AGI,__SD)])))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__AGI,__SD,__T,__TI],[__T,__TI])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',19,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',141,[__TI,11925]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',142,[__Tax,*(0.10000000000000001,__TI)])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',20,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',145,[__TI,11925]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',145,[__TI,48475]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',146,[__Tax,+(*(11925,0.10000000000000001),*(0.12,-(__TI,11925)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',21,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',150,[__TI,48475]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',150,[__TI,103350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',151,[__Tax,+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(0.22,-(__TI,48475)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',22,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',156,[__TI,103350]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',156,[__TI,197300]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',157,[__Tax,+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(0.23999999999999999,-(__TI,103350)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',23,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',163,[__TI,197300]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',163,[__TI,250525]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',164,[__Tax,+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(0.32000000000000001,-(__TI,197300)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',24,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',171,[__TI,250525]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',171,[__TI,626350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',172,[__Tax,+(+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250525,197300),0.32000000000000001)),*(0.34999999999999998,-(__TI,250525)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',25,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,single,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',180,[__TI,626350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',181,[__Tax,+(+(+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250525,197300),0.32000000000000001)),*(-(626350,250525),0.34999999999999998)),*(0.37,-(__TI,626350)))])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',26,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',192,[__TI,23850]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',193,[__Tax,*(0.10000000000000001,__TI)])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',27,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',196,[__TI,23850]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',196,[__TI,96950]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',197,[__Tax,+(*(23850,0.10000000000000001),*(0.12,-(__TI,23850)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',28,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',201,[__TI,96950]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',201,[__TI,206700]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',202,[__Tax,+(+(*(23850,0.10000000000000001),*(-(96950,23850),0.12)),*(0.22,-(__TI,96950)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',29,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',207,[__TI,206700]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',207,[__TI,394600]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',208,[__Tax,+(+(+(*(23850,0.10000000000000001),*(-(96950,23850),0.12)),*(-(206700,96950),0.22)),*(0.23999999999999999,-(__TI,206700)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',30,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',214,[__TI,394600]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',214,[__TI,501050]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',215,[__Tax,+(+(+(+(*(23850,0.10000000000000001),*(-(96950,23850),0.12)),*(-(206700,96950),0.22)),*(-(394600,206700),0.23999999999999999)),*(0.32000000000000001,-(__TI,394600)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',31,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',222,[__TI,501050]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',222,[__TI,751600]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',223,[__Tax,+(+(+(+(+(*(23850,0.10000000000000001),*(-(96950,23850),0.12)),*(-(206700,96950),0.22)),*(-(394600,206700),0.23999999999999999)),*(-(501050,394600),0.32000000000000001)),*(0.34999999999999998,-(__TI,501050)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',32,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',231,[__TI,751600]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',232,[__Tax,+(+(+(+(+(+(*(23850,0.10000000000000001),*(-(96950,23850),0.12)),*(-(206700,96950),0.22)),*(-(394600,206700),0.23999999999999999)),*(-(501050,394600),0.32000000000000001)),*(-(751600,501050),0.34999999999999998)),*(0.37,-(__TI,751600)))])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',33,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,qualifying_surviving_spouse,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_jointly,__TI,__Tax,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',34,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',250,[__TI,11925]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',251,[__Tax,*(0.10000000000000001,__TI)])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',35,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',254,[__TI,11925]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',254,[__TI,48475]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',255,[__Tax,+(*(11925,0.10000000000000001),*(0.12,-(__TI,11925)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',36,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',259,[__TI,48475]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',259,[__TI,103350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',260,[__Tax,+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(0.22,-(__TI,48475)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',37,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',265,[__TI,103350]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',265,[__TI,197300]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',266,[__Tax,+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(0.23999999999999999,-(__TI,103350)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',38,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',272,[__TI,197300]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',272,[__TI,250525]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',273,[__Tax,+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(0.32000000000000001,-(__TI,197300)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',39,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',280,[__TI,250525]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',280,[__TI,375800]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',281,[__Tax,+(+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250525,197300),0.32000000000000001)),*(0.34999999999999998,-(__TI,250525)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',40,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,married_filing_separately,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',289,[__TI,375800]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',290,[__Tax,+(+(+(+(+(+(*(11925,0.10000000000000001),*(-(48475,11925),0.12)),*(-(103350,48475),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250525,197300),0.32000000000000001)),*(-(375800,250525),0.34999999999999998)),*(0.37,-(__TI,375800)))])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',41,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',301,[__TI,17000]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',302,[__Tax,*(0.10000000000000001,__TI)])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',42,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',305,[__TI,17000]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',305,[__TI,64850]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',306,[__Tax,+(*(17000,0.10000000000000001),*(0.12,-(__TI,17000)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',43,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',310,[__TI,64850]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',310,[__TI,103350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',311,[__Tax,+(+(*(17000,0.10000000000000001),*(-(64850,17000),0.12)),*(0.22,-(__TI,64850)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',44,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',316,[__TI,103350]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',316,[__TI,197300]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',317,[__Tax,+(+(+(*(17000,0.10000000000000001),*(-(64850,17000),0.12)),*(-(103350,64850),0.22)),*(0.23999999999999999,-(__TI,103350)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',45,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',323,[__TI,197300]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',323,[__TI,250500]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',324,[__Tax,+(+(+(+(*(17000,0.10000000000000001),*(-(64850,17000),0.12)),*(-(103350,64850),0.22)),*(-(197300,103350),0.23999999999999999)),*(0.32000000000000001,-(__TI,197300)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',46,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',331,[__TI,250500]),','(fllibdelayedliteral(=<,'tax_1040_2024.ergo',331,[__TI,626350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',332,[__Tax,+(+(+(+(+(*(17000,0.10000000000000001),*(-(64850,17000),0.12)),*(-(103350,64850),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250500,197300),0.32000000000000001)),*(0.34999999999999998,-(__TI,250500)))]))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',47,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,head_of_household,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(>,'tax_1040_2024.ergo',340,[__TI,626350]),fllibdelayedliteral('\\is','tax_1040_2024.ergo',341,[__Tax,+(+(+(+(+(+(*(17000,0.10000000000000001),*(-(64850,17000),0.12)),*(-(103350,64850),0.22)),*(-(197300,103350),0.23999999999999999)),*(-(250500,197300),0.32000000000000001)),*(-(626350,250500),0.34999999999999998)),*(0.37,-(__TI,626350)))])),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?AGI',__AGI),=('?SD',__SD),=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?AGI',__AGI),=('?SD',__SD),=('?TI',__TI),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',48,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(tax_summary,__T,__Status,__AGI,__SD,__TI,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,__AGI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,__SD,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar8,__newvar1)),FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,__Status,__TI,__Tax,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar9,__newvar1)))))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',49,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_value,__T,filing_status,__Status,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',50,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_explanation,__T,filing_status,'Filing status is taken from the taxpayer''s declared filing_status fact.','_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,'_','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?AGI',__AGI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?AGI',__AGI)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',51,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_value,__T,agi,__AGI,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,__AGI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',52,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_explanation,__T,agi,'Adjusted Gross Income (AGI) is currently computed as total wage income only (prototype).','_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(agi,__T,'_','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?SD',__SD)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?SD',__SD)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',53,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_value,__T,standard_deduction,__SD,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,__SD,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',54,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_explanation,__T,standard_deduction,'The standard deduction equals the 2025 basic amount for the filing status plus any additional amount for age 65+ and/or blindness (traditional additional standard deduction only).','_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(standard_deduction,__T,2025,'_','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?TI',__TI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?TI',__TI)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',55,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_value,__T,taxable_income,__TI,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',56,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_explanation,__T,taxable_income,'Taxable income is AGI minus the standard deduction, floored at 0 if the deduction is larger than AGI.','_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,'_','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?TI',__TI),=('?Tax',__Tax)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T),=('?Tax',__Tax)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',57,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_value,__T,tax_liability,__Tax,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,__Status,__TI,__Tax,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Status,__T,__TI,__Tax],[__T,__Tax])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Status',__Status),=('?TI',__TI)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('tax_1040_2024.ergo'),'_$_$_ergo''descr_vars',58,['_$_$_ergo''prop_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_ergo''descr_vars'),'_$_$_ergo''tag_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_ergo''descr_vars'),'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),'_$_$_ergo''bool_descriptor'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME,strict,'_$_$_ergo''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(line_explanation,__T,tax_liability,'Tax liability is computed using the progressive 2025 tax brackets for the taxpayer''s filing status.','_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^tblflapply)(filing_status,__T,__Status,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^tblflapply)(taxable_income,__T,__TI,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),FLORA_THIS_WORKSPACE(d^tblflapply)(tax_liability,2025,__Status,__TI,'_','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)))),__newvar3,__newvar4,true,[null],[null],'_$_$_ergo''rule_enabled'(__newvar1,dynrule('tax_1040_2024.ergo'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Status,__T,__TI],[__T])],true)])))).


%%%%%%%%%%%%%%%%%%%%%%%%% Signatures for latent queries %%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%%%%%%%%% Queries found in the source file %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


 
#if !defined(FLORA_FLS2_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLS2_FILENAME  'tax_1040_2024.fls2'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLS2_FILENAME,FLORA_THIS_MODULE_NAME,'fls2'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_symbols_canonical_and_insert(FLORA_FLS2_FILENAME,FLORA_THIS_FLS_STORAGE,_SymbolErrNum))).
#endif

